A03: Program to develop Spell Bee Game
ShakthyTMM/Training pull request #26
Opened 2023-09-13 04:25 UTC by ShakthyTMM

2023-09-13 11:52 UTC, ravin-imm requested changes

2023-09-13 11:52 UTC, ravin-imm commented on Program.cs
> +List<string> resultList = new List<string> ();
Minor simplification. The above declaration can be written like below:
1. `var resultList = new List<string> ();`
2. `List<string> resultList = new ();`

2023-09-13 11:52 UTC, ravin-imm commented on Program.cs
> +int score = 0;
Can be:
`int point, score;`
The default value for an int is 0; So, no need to assign it to 0;

2023-09-13 11:52 UTC, ravin-imm commented on Program.cs
> +   foreach (var ch in list) {
Method name should start with a capital letter. Moreover, the name should be more apt. The name _isPangram_ (..) sounds like it checks if the given list is a pangram and returns a boolean.

2023-09-13 11:54 UTC, ravin-imm commented on Program.cs
> +   foreach (var ch in list) {
@ShakthyTMM : When I run the application, I see that the words are not getting sorted (as shown below) when we shuffle the words list and loaded it:
![image](https://github.com/ShakthyTMM/Training/assets/75829870/c115c899-b931-4310-a9ea-26d32fbd87b2)

2023-09-14 10:06 UTC, ravin-imm requested changes

2023-09-14 10:06 UTC, ravin-imm commented on Program.cs
> +   foreach (var ch in list) {
You are passing the list of words here. This is not required as the list a member variable and can be accessed by this function as you are accessing point and score. I think you are just finding out only the first pangram and returning it. This works for the above selected letters as there is only one pangram in this case. To test this further, please use the below letters and check if you get the correct sorted list:
![image](https://github.com/ShakthyTMM/Training/assets/75829870/af01c681-21fe-40bb-9e11-02d667b9278c)

**_Note_**: The total score in this case should be 3046.

2023-09-14 10:06 UTC, ravin-imm commented on Program.cs
> +      resultList.Add (word);
This can be simplified as:
`if (word.Length >= 4 && word.Contains (letters[0]) && word.All (letters.Contains)) resultList.Add (word);`

2023-09-19 04:40 UTC, ravin-imm requested changes

2023-09-19 04:40 UTC, ravin-imm commented on Program.cs
> +(int, bool, string) GetScore (string word) {
Good that you have used a tuple to get the necessary information. Best practice is to name the return types instead of just returning its types. Moreover, as a convention the name would start with a capital letter. So, the above can be written as:
_**(int Score, bool Pangram, string Word) GetScore (string word) {
...
...
}**_

This looks more cleaner when you try to access any of these return types. For instance, in the below line:
_**if (word.Pangram) ForegroundColor = ConsoleColor.Green;**_
Here instead of _Item2_, _Pangram_ would be more apt for readability.

2023-09-19 04:40 UTC, ravin-imm commented on Program.cs
> +                               .OrderBy (x => x.Item3).OrderByDescending (x => x.Item1).ToList ();
To extend your understanding the above LINQ queries, try to first _OrderByDescending (..)_ and then order by the word. Check if you get the desired sorted words list.

2023-09-19 04:40 UTC, ravin-imm commented on Program.cs
> +   int point;
_point_ looks little confusing as we use this for a point in geometry. Use score here and while calculating the score for complete list it can be total score.

2023-09-19 09:34 UTC, ShakthyTMM commented on Program.cs
> +                               .OrderBy (x => x.Item3).OrderByDescending (x => x.Item1).ToList ();
OrderBy is for taking the pangrams and printing them first. In the latest commit I have sorted the words of same score.

2023-09-19 09:50 UTC, ravin-imm requested changes

2023-09-19 09:50 UTC, ravin-imm commented on Program.cs
> +   bool Pangram = Letters.All (Word.Contains);
The local names should start with small letters. I think you misunderstood my previous message. You can here return (score, pangram, word). But, the capitalization should be only while naming the return types.

2023-09-19 09:50 UTC, ravin-imm commented on Program.cs
> +                               .OrderBy (x => x.Pangram).OrderByDescending (x => x.Score).ThenBy (x => x).ToList ();
Here I think you need not order by if the word is a pangram as we already order them based on the score and all the pangrams would have an extra score of 7.

2023-09-19 09:50 UTC, ravin-imm commented on Program.cs
> +var validWords = File.ReadAllLines ("C:/Users/shakthy.r/Downloads/words-shuffle.txt")
Generally the file paths should not be absolute. For me, to check your application, I have to change the file path here as I won't be having the above path. From, next assignments try to think where to place such files.

2023-09-19 11:18 UTC, ravin-imm approved these changes

2023-09-19 11:19 UTC, closed without merging